# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import yaksh.models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0012_release_0_8_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, default=None, help_text='Please upload video files in mp4, ogv, webm format', null=True, upload_to=yaksh.models.get_file_dir),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='file',
            field=models.FileField(default=None, upload_to=yaksh.models.get_file_dir),
        ),
        migrations.AlterUniqueTogether(
            name='testcaseorder',
            unique_together=set([('answer_paper', 'question', 'order')]),
        ),
    ]
