# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models


def set_is_moderator(apps, schema_editor):
    """ Set is_moderator to True for all users that belong
    to Moderator group """

    Profile = apps.get_model('yaksh', 'Profile')
    for prof in Profile.objects.all():
        user = prof.user
        if user.groups.filter(name='moderator').exists():
            prof.is_moderator = True
            prof.save()


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0013_auto_20180713_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_moderator),
    ]
